sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lijiayi20021027

#  alioss:
#    endpoint: yourEndpoint
#    access-key-id: yourAccessKeyId
#    access-key-secret: yourAccessKeySecret
#    bucket-name: yourBucketName
